/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  project?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "project";
  };
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  text?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  views?: number;
  description?: string;
  category?: string;
  image?: string;
  image2?: string;
  image3?: string;
  pitch?: string;
  techStack?: Array<string>;
  githubUrl?: string;
  upvotes?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  username?: string;
  email?: string;
  image?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Comment | Project | Author | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && (defined(slug.current) && (!defined($search) || title match $search || category match $search || author->name match $search))] | order(_createdAt desc) {  _id,   title,   slug,   _createdAt,   author -> {    _id, name, image, bio  },   views,  description,   category,  image,  pitch,  techStack,  githubUrl,  upvotes}
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  views: number | null;
  description: string | null;
  category: string | null;
  image: string | null;
  pitch: string | null;
  techStack: Array<string> | null;
  githubUrl: string | null;
  upvotes: number | null;
}>;
// Variable: PROJECT_BY_ID_QUERY
// Query: *[_type == "project" && _id == $id][0]{  _id,   title,   slug,   _createdAt,   author -> {    _id, name, username, image, bio  },   views,  description,   category,  image,  image2,  image3,  pitch,  techStack,  githubUrl,  upvotes,  "comments": *[_type == "comment" && project._ref == ^._id] | order(_createdAt desc) {    _id,    text,    _createdAt,    author -> {      _id, name, image    }  }}
export type PROJECT_BY_ID_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    username: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  views: number | null;
  description: string | null;
  category: string | null;
  image: string | null;
  image2: string | null;
  image3: string | null;
  pitch: string | null;
  techStack: Array<string> | null;
  githubUrl: string | null;
  upvotes: number | null;
  comments: Array<{
    _id: string;
    text: string | null;
    _createdAt: string;
    author: {
      _id: string;
      name: string | null;
      image: string | null;
    } | null;
  }>;
} | null;
// Variable: PROJECT_VIEWS_QUERY
// Query: *[_type == "project" && _id == $id][0]{    _id, views  }
export type PROJECT_VIEWS_QUERYResult = {
  _id: string;
  views: number | null;
} | null;
// Variable: AUTHOR_BY_ID_QUERY
// Query: *[_type == "author" && _id == $id][0] {  _id,  id,  name,  username,  email,  image,  bio}
export type AUTHOR_BY_ID_QUERYResult = {
  _id: string;
  id: number | null;
  name: string | null;
  username: string | null;
  email: string | null;
  image: string | null;
  bio: string | null;
} | null;
// Variable: PROJECTS_BY_AUTHOR_QUERY
// Query: *[_type == "project" && author._ref == $id] | order(_createdAt desc) {  _id,   title,   slug,   _createdAt,   author -> {    _id, name, image, bio  },   views,  description,   category,  image,  pitch,  techStack,  githubUrl,  upvotes}
export type PROJECTS_BY_AUTHOR_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  views: number | null;
  description: string | null;
  category: string | null;
  image: string | null;
  pitch: string | null;
  techStack: Array<string> | null;
  githubUrl: string | null;
  upvotes: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"project\" && (defined(slug.current) && (!defined($search) || title match $search || category match $search || author->name match $search))] | order(_createdAt desc) {\n  _id, \n  title, \n  slug, \n  _createdAt, \n  author -> {\n    _id, name, image, bio\n  }, \n  views,\n  description, \n  category,\n  image,\n  pitch,\n  techStack,\n  githubUrl,\n  upvotes\n}": PROJECTS_QUERYResult;
    "*[_type == \"project\" && _id == $id][0]{\n  _id, \n  title, \n  slug, \n  _createdAt, \n  author -> {\n    _id, name, username, image, bio\n  }, \n  views,\n  description, \n  category,\n  image,\n  image2,\n  image3,\n  pitch,\n  techStack,\n  githubUrl,\n  upvotes,\n  \"comments\": *[_type == \"comment\" && project._ref == ^._id] | order(_createdAt desc) {\n    _id,\n    text,\n    _createdAt,\n    author -> {\n      _id, name, image\n    }\n  }\n}": PROJECT_BY_ID_QUERYResult;
    "\n  *[_type == \"project\" && _id == $id][0]{\n    _id, views  \n}": PROJECT_VIEWS_QUERYResult;
    "\n*[_type == \"author\" && _id == $id][0] {\n  _id,\n  id,\n  name,\n  username,\n  email,\n  image,\n  bio\n}  \n": AUTHOR_BY_ID_QUERYResult;
    "\n*[_type == \"project\" && author._ref == $id] | order(_createdAt desc) {\n  _id, \n  title, \n  slug, \n  _createdAt, \n  author -> {\n    _id, name, image, bio\n  }, \n  views,\n  description, \n  category,\n  image,\n  pitch,\n  techStack,\n  githubUrl,\n  upvotes\n}\n": PROJECTS_BY_AUTHOR_QUERYResult;
  }
}
